# Materiaal en methoden

## Vertaling van de scores naar een rangschikking van milieudrukken

### Verkenning van de antwoorden op de vragen

De antwoorden bestaan uit een *score*, een *betrouwbaarheidswaarde* en een beknopte tekstuele *uitleg*.
De antwoorden zijn ingelezen en verwerkt in de software-omgeving R (zie Bijlage \@ref(app:sessioninfo)).
Hiervan zijn de volgende verkenningen gebeurd:

- nagaan van de **spreiding van de scores** per vraag, over alle milieudrukken. Op die manier gebeurt een algemene kwaliteitscheck van de resultaten en wordt een eerste indruk bekomen van hoe zeer de vragen verschillende milieudrukken onderscheiden;
- nagaan van de **spreiding van de betrouwbaarheid** van het antwoord per vraag, over alle milieudrukken.
Op deze manier is het mogelijk om te checken in welke mate kennishiaten optreden.
In verschillende gevallen zijn deze hiaten pertinent.
In andere gevallen zijn mogelijks nog beperkte verbeteringen mogelijk door verder op zoek te gaan naar bestaande kennis in Vlaanderen;
- nagaan van de ordinale **correlatie tussen de vragen**, op basis van de Kendall correlatiecoëfficiënt.
Dit dient om na te gaan hoeveel onderlinge redundantie optreedt tussen de vragen _in hun onderscheiding tussen milieudrukken_.
Gedeeltelijke redundantie tussen twee vragen in hun discriminerend vermogen betekent echter niet automatisch dat de relevantie van elk van deze vragen voor de rangschikking kleiner is.
Zulke vragen kunnen nog steeds, omwille van hun inhoudelijke betekenis, elk evenveel -- of volgens een gekozen sleutel -- *meewegen* op de rangschikking.

Een tabulaire oplijsting van alle antwoorden per milieudruk is te vinden in Bijlage \@ref(app:fiches).


### Rangschikking van milieudrukken

Er zijn verschillende manieren om de milieudrukken te rangschikken op basis van de scores:

- de meest zinvolle lijkt een beleidsrelevante, bewuste keuze van welke vragen meer zouden moeten meespelen dan andere, uitgedrukt als (relatieve) gewichten, zodat op basis daarvan een **gewogen eindscore** kan worden berekend per milieudruk.
We beschouwen daarom twee scenario's om een goede bespreking op te kunnen baseren:
    - één scenario (**scenario 1**) dat de nadruk legt op de noodzaak aan een programmatische aanpak, bekeken vanuit de huidige problemen om de _instandhoudingsdoelstellingen_ te bereiken (milieu: vraagA1; beleidsinstrumenten: vraag B2b) -- hoe hoger deze problematiek, hoe meer noodzakelijk;
    - één scenario (**scenario 2**) dat de nadruk legt op de _relatieve eenvoud_ om een programmatische aanpak te kunnen implementeren, vooral gericht op de mogelijkheid van brongerichte maatregelen (vraag M1) en op de beschikbaarheid aan basisinformatie (vragen T1 en T4).
- een basisalternatief (bv. ter referentie) is om elke vraag evenveel te wegen in de berekening van een zg. **ongewogen eindscore**.

De eindscore per milieudruk wordt in alle gevallen berekend als de 'gemiddelde' score voor de 8 vragen: hetzij een ongewogen gemiddelde, hetzij een gewogen gemiddelde.
Om gemakkelijke vergelijking toe te laten, zijn deze eindscores tevens omgezet naar een rangnummer.

In Tabel \@ref(tab:gewichttabel) wordt aangegeven welke gewichten voor elk scenario zijn gebruikt voor de berekening van de eindscore.
In de tabel zijn de vragen benoemd met het label, zoals dit terugkeert in verschillende resultaten.

```{r gewichttabel, results='asis'}
gewichten <-
    tribble(
      ~Vraag,            ~Ongewogen, ~Scenario_1,   ~Scenario_2,
      "A1_problematiek", 1, 10, 2,
      "A2a_actieradius", 1, 2, 2,
      "A2b_geogr_spreiding", 1, 5, 2,
      "A4_complexiteit", 1, 4, 5,
      "B2b_tekort_beleidsinstrum", 1, 7, 5,
      "M1_bronger_maatreg", 1, 5, 10,
      "T1_informatie", 1, 5, 10,
      "T4_grenswaarden", 1, 2, 7
) %>%
    mutate(Vraag = factor(Vraag))
gewichten %>%
    pandoc.table(
      caption = "(\\#tab:gewichttabel)Gekozen gewichten per vraag. De waarden zijn relatief te beschouwen.",
      split.table = Inf ,
      justify = "left"
    )
```

Daarnaast is het ook mogelijk om automatische criteriaweging te laten gebeuren op basis van de correlatie tussen vragen, dus op basis van de variatie tussen de milieudrukken.
Hiertoe is een principale componentenanalyse (PCA) uitgevoerd.
Een ordinatie-as (principale component) vat de informatie dan samen op een zodanige manier dat dit maximaal de -- voor alle vragen gezamenlijke -- variatie tussen de milieudrukken weergeeft.

Het lijkt ons echter _niet zo zinvol_ om PCA als basis voor rangschikking te gebruiken, want deze benadering laat toe dat vragen op een niet-beleidsrelevante manier gewogen worden.
De resultaten van een PCA-ordinatie worden wel weergegeven, maar dienen alleen om de variatie tussen milieudrukken in relatie tot de vragen visueel weer te geven.




